name: Export PDF with Cover

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libxss1 \
            libasound2 \
            fonts-liberation \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            libx11-xcb1 \
            xdg-utils

      - name: Install markdown-pdf and puppeteer
        run: npm install -g markdown-pdf puppeteer

      - name: Generate PDF with cover
        run: |
          mkdir -p output
          echo "<html><head><style>body {font-family:sans-serif;}</style></head><body><h1>DAO-GOGS Systemtled</h1></body></html>" > output/cover.html
          markdown-pdf README.md \
            --paper-format A4 \
            --prepend output/cover.html \
            --out output/DAO-GOGS-Docs.pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: DAO-GOGS-PDF
          path: output/DAO-GOGS-Docs.pdf
